language: node_js
node_js:
  - 12
  - 14
  - 16
matrix:
  allow_failures:
  - node_js: "12"
script:
  - npm run lint
  - npm test
  - npm run check-coverage
after_script:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
